generator:
  class: sfDoctrineGenerator
  param:
    model_class:           timpanyProduct
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          timpany_product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        class_name: {label: "Product type"}
      list:
      filter:  ~
      form:
        fields:
          class_name: {help: "class_name: name of the class this product is an instance of."}
        display:
          - name
          - description
          - article_number
          - net_price
          - inventory
          - class_name
          - slug
          - categories_list
      edit:    ~
      new:     ~
