# Special case for the home page

default:
  url:   /admin/:module/:action/*

homepage:
  url:  /
  param: { module: a, action: show, slug: / }

# The non-CMS actions of your project, and the admin actions of the CMS
a_action:
  url:   /cms/:module/:action

# shop pages
timpany_index:
  url:   /shop
  param: { module: timpany, action: index }
timpany_category:
  url:   /shop/:category
  param: { module: timpany, action: index }
  requirements: { category: .* }
timpany_product:
  url:   /shop/:category/:product
  param: { module: timpany, action: showProduct }
  requirements: { category: .*, product: .* }
timpany_cart_add:
  url:   /cart/add/:product
  param: { module: timpany, action: addToCart }
  requirements: { product: .* }
timpany_cart_remove:
  url:   /cart/remove/:product
  param: { module: timpany, action: removeCartItem }
  requirements: { product: .* }
timpany_cart:
  url:   /cart
  param: { module: timpany, action: cart }
timpany_checkout:
  url:   /checkout
  param: { module: timpany, action: checkout }

# Must be the LAST rule
a_page:
  url:   /:slug
  param: { module: a, action: show }
  requirements: { slug: .* }
