<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Timpany
 * @subpackage model
 * @author     The Timpany Core Team <lsdug@googlegroups.com>
 */
class sfGuardUser extends PluginsfGuardUser
{
}
