<?php

/**
 * sfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
<<<<<<< HEAD
 * @package    timpany
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
=======
 * @package    Timpany
 * @subpackage model
 * @author     The Timpany Core Team <lsdug@googlegroups.com>
>>>>>>> b82443d... Cleaning up the project (V): code formatting and whitespace cleanup
 */
class sfGuardRememberKey extends PluginsfGuardRememberKey
{
}
