<?php

/**
 * PlugintimpanyCategoryProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyCategoryProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyCategoryProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyCategoryProducts');
    }
}