<?php

/**
 * PlugintimpanyUserCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyUserCartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyUserCartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyUserCart');
    }
}