<?php

/**
 * PlugintimpanyTaxClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyTaxClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyTaxClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyTaxClass');
    }
    
    public function getFullTaxClass()
    {
    	return $this->findById(1);
    }
    
    public function getReducedTaxClass()
    {
      return $this->findById(2);
    }
}