<?php

/**
 * PlugintimpanyOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugintimpanyOrder extends BasetimpanyOrder implements timpanyOrderInterface
{
	protected $gross_sum=null;
	
	/**
	 * create payment for order
	 * @return Payment
	 */
  public function createPayment()
  {
    sfContext::getInstance()->getLogger()->log('Zahlung wird angelegt', 6);
  	$paymentData = PaymentDataTable::getInstance()->create(array(
  		'method_class_name' => 'PaypalPayment',
  		'subject'			=> 'Order #' . $this->getId()
  	));
  	sfContext::getInstance()->getLogger()->log('Zahlungsdaten zusammengestellt', 6);
    $payment = Payment::create($this->getGrossSum(), 'EUR', new PaypalPaymentData(array(
      'subject'     => 'Order #' . $this->getId(),
      'username'    => 'quafzi_1282422503_biz_api1.netextreme.de',
      'password'    => '1282422508',
      'signature'   => 'A6xwvNuPnHQVIia8cnUqI2EXX9JWA7AbKPJCGjz0MmzFT7rKMF-ZKyoj' 
    )));
    sfContext::getInstance()->getLogger()->log('Zahlung wurde angelegt', 6);
    $payment->setOrder($this);
    sfContext::getInstance()->getLogger()->log('Zahlung wurde mit Bestellung verknüpft', 6);
    $payment->save();
    sfContext::getInstance()->getLogger()->log('Zahlung gespeichert', 6);
    return $payment;
  }
  
  public function getState()
  {
  	return parent::_get('state');
  }
  
  public function getGrossSum()
  {
  	if (true or is_null($this->gross_sum)) {
	  	$this->gross_sum=0;
	    foreach ($this->getItems() as $item) {
	    	$this->gross_sum += $item->getGrossSum();
	    } 
  	}
  	return $this->gross_sum; 	
  }
  
  public function addProduct(timpanyProductInterface $product, $count=1) {
  	return $this->addItem($product, $count);
  }
  
  /**
   * add a product to the order
   * 
   * @param timpanyProductInterface $product
   * @param int                     $count
   */
  public function addItem(timpanyProductInterface $product, $count)
  {
      $itemRelation   = $this->getTable()->getRelation('Items');
      if ($this->exists()) {
        $itemCollection = $itemRelation['table']->findByOrderId($this->getId());
        $is_new_item = true;
        foreach ($itemCollection as $item) {
          if ($product->getId() === $item->getProductId()) {
            $is_new_item = false;
            break;
          }
        }
      } else {
      	$is_new_item = true;
      }
      if ($is_new_item) {
        $item = new timpanyOrderItem();
        $item->setProduct($product);
        $item->setOrder($this);
      }
      $item->setCount($item->setCount() + $count);
      $this->save();
  }
  
  /**
   * clear cart
   * 
   * FIXME: not yet implemented
   */
  public function clear()
  {
  }
  
  /**
   * set cart items
   * @param array $items
   * 
   * FIXME: not yet implemented
   */
  public function setItems($items)
  {
  }
  
  /**
   * get count of a specific product
   * @param timpanyProductInterface $product
   * 
   * @return int Count of product
   * 
   * FIXME: not yet implemented
   */
  public function getCountOfProduct(timpanyProductInterface $product)
  {
  	
  }

  /**
   * get cart items
   * @return array Array with following structure:
   *       'count'     => integer,
   *       'product'   => timpanyProductInterface,
   *       'net_sum'   => float
   *       'gross_sum' => float
   * 
   * FIXME: not yet implemented
   */
  public function getItems()
  {
  	return parent::_get('Items');
  }

  /**
   * get net sum
   * @return float
   * 
   * FIXME: not yet implemented
   */
  public function getNetSum()
  {
  	
  }
  
  /**
   * remove item from cart
   * @param string $key Key of items collection
   * FIXME: not yet implemented
   */
  public function removeItem($key)
  {
  	
  }
  
  /**
   * get count of products
   * @return int
   * 
   * FIXME: not yet implemented
   */
  public function getProductCount()
  {
  	
  }

  /**
   * get count of items
   * @return int
   * 
   * FIXME: not yet implemented
   */
  public function getItemCount()
  {
  	
  }
  
  /**
   * turn order into an array
   * 
   * @link http://www.doctrine-project.org/documentation/manual/1_1/en/working-with-models
   * @param boolean $deep         whether to include relations
   * @param boolean $prefixKey    not used
   * @return array
   * 
   * FIXME: not yet implemented
   */
  public function toArray($deep=true, $prefixKey = false)
  {
  	
  }
}
