<?php

/**
 * PlugintimpanyOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugintimpanyOrder extends BasetimpanyOrder
{
	protected $gross_sum=null;
	
  public function createPayment()
  {
  	$paymentData = PaymentDataTable::getInstance()->create(array(
  		'method_class_name' => 'PaypalPayment',
  		'subject'			=> 'Order #' . $this->getId()
  	));
    $payment = Payment::create($this->getGrossSum(), 'EUR', $paymentData);
    $payment->setOrder($this);
    $payment->save();
  }
  
  public function getGrossSum()
  {
  	if (true or is_null($this->gross_sum)) {
	  	$this->gross_sum=0;
	    foreach ($this->getItems() as $item) {
	    	$this->gross_sum += $item->getGrossSum();
	    } 
  	}
  	return $this->gross_sum; 	
  }
}
