<?php

/**
 * PlugintimpanyOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyOrderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyOrderState');
    }
}