<?php

/**
 * PlugintimpanyOrderProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyOrderProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyOrderProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyOrderProducts');
    }
}