<?php

/**
 * PlugintimpanyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyCategory');
    }
}