<?php

/**
 * PlugintimpanyTaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyTaxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyTaxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyTax');
    }
}