<?php

/**
 * PlugintimpanyCategoryProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyCategoryProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyCategoryProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyCategoryProduct');
    }
}