<?php

/**
 * PlugintimpanyProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyProduct');
    }
}