<?php

/**
 * PlugintimpanyOrderProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyOrderProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyOrderProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyOrderProduct');
    }
}