<?php

/**
 * PlugintimpanyUserCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugintimpanyUserCart extends BasetimpanyUserCart
{
	/**
	 * get count of cart products
	 * 
	 * @return int
	 */
  public function getProductCount()
  {
  	$count = 0;
  	foreach ($this->getItems() as $item) {
  		$count += $item->getCount();
  	}
  	return $count;
  }
  
  /**
   * get count of cart items
   * 
   * @return int
   */
  public function getItemCount()
  {
  	return $this->getItems()->count();
  }
  
  /**
   * add product
   * 
   * @param timpanyProductInterface $product
   * @param int                     $count
   * 
   * @return timpanyCartInterface
   */
  public function addProduct(timpanyProductInterface $product, $count) {
  	$cartItem = new timpanyCartItem(array('count' => $count, 'product' => $product->toCartItem()));
  	$this->getItems()->add($cartItem);
  	return $this;
  }
}