<?php

/**
 * PlugintimpanyOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintimpanyOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintimpanyOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintimpanyOrder');
    }
    
    public function createOrder(timpanyCartInterface $cart)
    {
        $order = self::create();
        $order->setNetSum($cart->getNetSum());
        foreach ($cart->getItems() as $item)
        {
        	  $frozen_data = $item->getProductData();
        	  if (is_array($frozen_data)) {
        	  	$frozen_data = json_encode($frozen_data);
        	  }
            $orderItem = timpanyOrderItemTable::getInstance()->create(array(
                'count'       => $item->getCount(),
                'frozen_data' => $frozen_data,
            ));
            
            $order->getItems()->add($orderItem);
        }
        return $order;
    }
}