<?php

/**
 * PluginaNewRichTextSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaNewRichTextSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaNewRichTextSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaNewRichTextSlot');
    }
}