<?php

/**
 * PluginaRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaRedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaRedirect');
    }
    
    public function update($fromSlug, $toPage)
    {
      $redirect = $this->createQuery('r')->where('r.slug = ?', array($fromSlug))->fetchOne();
      if (!$redirect)
      {
        $redirect = new aRedirect();
        $redirect->slug = $fromSlug;
      }
      $redirect->page_id = $toPage->id;
      $redirect->save();
    }
}