<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaImageSlot extends BaseaImageSlot
{
  public function isOutlineEditable()
  {
    return false;
  }
  // We don't need refreshSlot anymore thanks to ON DELETE CASCADE
  // and the new simplified non-API-driven setup
}
