<?php

/**
 * PluginaBlogSingleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBlogSingleSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBlogSingleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBlogSingleSlot');
    }
}