<?php

/**
 * PluginaBlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginaBlogPost extends BaseaBlogPost
{
  public $engine = 'aBlog';
  
  public function getVirtualPageSlug()
  {
    return '@a_blog_search_redirect?id=' . $this->id;
  }
}