<?php

/**
 * PluginaBlogCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginaBlogCategory extends BaseaBlogCategory
{

  public function getNumBlogItems()
  {
    return count($this->BlogItems);
  }
  
  public function getNumUsers()
  {
    return count($this->Users);
  }

  public function getNumBlogPosts()
  {
    return Doctrine::getTable('aBlogCategory')->createQuery()
      ->innerJoin('aBlogCategory.BlogItems')
      ->addWhere('aBlogCategory.id = ?', $this['id'])
      ->addWhere('aBlogCategory.BlogItems.type = ?', 'post')
      ->count();
  }

  public function getNumEvents()
  {
    return Doctrine::getTable('aBlogCategory')->createQuery()
      ->innerJoin('aBlogCategory.BlogItems')
      ->addWhere('aBlogCategory.id = ?', $this['id'])
      ->addWhere('aBlogCategory.BlogItems.type = ?', 'event')
      ->count();
  }
  
}