<?php

/**
 * PluginaEventSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEventSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEventSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEventSlot');
    }
}