<?php

/**
 * PluginaBlogSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBlogSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBlogSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBlogSlot');
    }
}