<?php

/**
 * PluginaEventSingleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEventSingleSlotTable extends aSlotTable
{
  protected $editDefault = true;
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEventSingleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEventSingleSlot');
    }
}