<?php

/**
 * timpanyUserCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Timpany
 * @subpackage model
 * @author     The Timpany Core Team <lsdug@googlegroups.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class timpanyUserCart extends PlugintimpanyUserCart
{
}
