<?php

/**
 * timpanyProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    timpany
 * @subpackage model
 * @author     Thomas Kappel <quafzi@netextreme.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class timpanyProduct extends PlugintimpanyProduct
{

}
